"""The corruption stage: a deliberately dirtied twin of the blind tree.

A clean synthetic room is the biggest measurement risk this project
carries: tidy filenames, a seller who never misfiles, text with every
signature phrase intact. A classifier scored only against that learns —
and is credited for — regularities no real room has. This module writes
a derived `corrupted/` view of the room that degrades the classifier's
three signals the way a real room degrades them, while the ground truth
stays exact:

  - **renaming** — version tags, FINAL/clean suffixes, case mangling,
    separator swaps and typos on a fraction of filenames;
  - **misfiling** — a fraction of documents moved to the wrong top-level
    folder, because the seller's own filing is the strongest signal a
    classifier leans on and real sellers get it wrong;
  - **OCR-style noise** — character confusions (l/1, O/0, S/5, …) and
    whitespace damage in a fraction of markdown documents, at a per-
    character rate, so content signatures fail the way they fail on a
    real scan. CSV content is never noised: structured data with broken
    cells is unusable, not realistic — a csv may be renamed or misfiled,
    but its cells stay intact;
  - **truncation** — a fraction of long documents cut short, the missing-
    schedules shape: a real truncated scan just ends.

The output mirrors the `subset/` conventions: written at the room root
as a derived, regenerable view (never part of the blind tree, so no gate
walks it) — `corrupted/` by default, or wherever `--out` points, so two
profiles of one room can stand side by side (`corrupted-light/`,
`corrupted-heavy/`) instead of the second replacing the first —
carrying its own ownership marker so a rebuild may delete it
and nothing else, and deterministic — every per-file decision comes from
a sha256 over (seed, path, purpose), and the per-character stream from a
`random.Random` seeded the same way, so the same (room, seed, profile)
is byte-identical and a scorecard can name the exact corrupted room it
ran against. Alongside the tree it writes:

  - `corrupted/answer-key.jsonl` — the room's key with every path
    rewritten to its corrupted spelling. The mess moves the paths; it
    never moves the truth.
  - `corrupted/log.jsonl` — one row per document: original path,
    corrupted path, and which corruptions were applied. The audit trail
    that lets a surprising eval number be traced to what corruption did.

On the build plan's fixed tooling (Augraphy + nlpaug): Augraphy degrades
document *images*, and this pipeline is markdown-first — its render
stage produces born-digital DOCX/PDF, not scans — so the image-stage
corruption belongs with a scanned-render stage when one exists, as a new
profile here. nlpaug's OCR augmenter is at heart a character-confusion
table; this module carries that table in-repo, seeded and dependency-
free, rather than adding a numpy-sized dependency for it. The profile
mechanism is the seam both slot into.
"""

from __future__ import annotations

import hashlib
import json
import random
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from .answer_key import ANSWER_KEY_NAME
from .ownership import (
    NotOwnedError,
    UnsafeOutDirError,
    assert_safe_out_dir,
    assert_target_is_ours,
    write_marker,
)
from .roomconf import RoomConf

CORRUPTED_DIR = "corrupted"
LOG_NAME = "log.jsonl"

CORRUPT_MARKER_NAME = ".synthvdr-corrupted"
CORRUPT_MARKER_TEXT = (
    "Generated by synthvdr (synthvdr/corrupt.py). This whole directory is "
    "deleted and rebuilt on every corruption run, so nothing here is safe "
    "to edit or store. Removing this marker file makes the directory "
    "un-rebuildable in place: synthvdr refuses to delete a non-empty "
    "directory it cannot prove it created, and will stop rather than "
    "destroy your data.\n"
)

DOC_SUFFIXES = (".md", ".csv")

# Rates are fractions of documents (noise_char_rate is per character).
# "light" is a plausibly well-run modern deal; "heavy" is the messy
# carve-out room every classifier eventually meets.
PROFILES: Dict[str, Dict[str, float]] = {
    "light": {
        "rename_rate": 0.20,
        "misfile_rate": 0.03,
        "noise_rate": 0.10,
        "noise_char_rate": 0.01,
        "truncate_rate": 0.02,
    },
    "heavy": {
        "rename_rate": 0.50,
        "misfile_rate": 0.10,
        "noise_rate": 0.30,
        "noise_char_rate": 0.03,
        "truncate_rate": 0.08,
    },
}

# The classic OCR confusions, both directions where both directions
# happen. Multi-character confusions (rn->m) are deliberately absent:
# they change string length mid-stream, which makes the damage rate
# drift from the configured one.
_CONFUSIONS = {
    "l": "1", "1": "l", "O": "0", "0": "O", "S": "5", "5": "S",
    "B": "8", "e": "c", "o": "0", "i": "l", "t": "f", "a": "o",
}

_RENAME_TAGS = [
    " v2", " v4", " FINAL", " final clean", " (1)", " (conformed copy)",
    " - execution version", " v3 FINAL FINAL",
]

# Truncation keeps this fraction of a document's lines (picked per file
# from the range) — the missing-schedules shape: the document just ends.
_TRUNCATE_KEEP = (0.55, 0.75)
_TRUNCATE_MIN_LINES = 30


class CorruptError(Exception):
    """The room cannot be corrupted safely, or its key cannot follow."""


@dataclass(frozen=True)
class CorruptReport:
    documents: int
    renamed: int
    misfiled: int
    noised: int
    truncated: int
    out: Path


def _h(seed: int, *parts: str) -> int:
    joined = "|".join([str(seed), *parts])
    return int.from_bytes(hashlib.sha256(joined.encode("utf-8")).digest()[:8], "big")


def _hits(seed: int, rel: str, purpose: str, rate: float) -> bool:
    return (_h(seed, rel, purpose) % 10_000) < int(rate * 10_000)


def _rename(seed: int, rel: str, stem: str) -> str:
    variant = _h(seed, rel, "rename-variant") % 4
    if variant == 0:
        return stem + _RENAME_TAGS[_h(seed, rel, "rename-tag") % len(_RENAME_TAGS)]
    if variant == 1:
        return stem.upper()
    if variant == 2:
        swapped = stem.replace("-", " ") if "-" in stem else stem.replace("_", " ")
        return swapped if swapped != stem else stem.replace(" ", "_")
    if len(stem) > 4:
        drop = _h(seed, rel, "rename-typo") % (len(stem) - 2) + 1
        return stem[:drop] + stem[drop + 1 :]
    return stem + " (1)"


def _noise(seed: int, rel: str, text: str, char_rate: float) -> str:
    rng = random.Random(_h(seed, rel, "noise-stream"))
    out = []
    for ch in text:
        if ch in _CONFUSIONS and rng.random() < char_rate:
            out.append(_CONFUSIONS[ch])
        elif ch == " " and rng.random() < char_rate / 2:
            out.append("  ")
        else:
            out.append(ch)
    return "".join(out)


def _truncate(seed: int, rel: str, text: str) -> Tuple[str, bool]:
    lines = text.splitlines(keepends=True)
    if len(lines) < _TRUNCATE_MIN_LINES:
        return text, False
    low, high = _TRUNCATE_KEEP
    keep = low + (high - low) * ((_h(seed, rel, "truncate-keep") % 1000) / 1000)
    return "".join(lines[: max(1, int(len(lines) * keep))]), True


def _load_key_rows(room: Path, conf: RoomConf) -> List[dict]:
    key_path = room / conf.get_relative_path("KEY_ROOT") / ANSWER_KEY_NAME
    if not key_path.is_file():
        raise CorruptError(
            f"no {ANSWER_KEY_NAME} at {key_path} — corruption rewrites the "
            "key's paths to follow the mess, so build the key first: "
            "python3 -m synthvdr answerkey"
        )
    rows = []
    for n, line in enumerate(key_path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError as exc:
            raise CorruptError(
                f"{key_path}: line {n} is not valid JSON ({exc}) — rewrite "
                "the key with python3 -m synthvdr answerkey"
            ) from exc
    return rows


def corrupt_room(
    room: Path,
    conf: RoomConf,
    seed: int,
    profile: Dict[str, float],
    out_dir: Optional[Path] = None,
) -> CorruptReport:
    """Write the corrupted twin — tree, rewritten answer key, and log.

    `out_dir` defaults to `corrupted/` at the room root. Pass one per
    profile (`corrupted-light/`, `corrupted-heavy/`) to keep two twins of
    the same room: the default is a fixed name, so a second run replaces
    the first. Whatever the target, it is deleted and rebuilt, so it must
    be a directory this tool created and must not be, contain or sit
    inside any configured tree or the room root — the same rule as
    subset's out_dir, shared from synthvdr.ownership.
    """
    blind_root = room / conf.get_relative_path("BLIND_TREE")
    if not blind_root.is_dir():
        raise CorruptError(f"no blind tree at {blind_root} — nothing to corrupt")

    key_rows = _load_key_rows(room, conf)
    key_by_path = {row["source_path"]: row for row in key_rows}

    files = sorted(p for p in blind_root.rglob("*") if p.is_file())
    docs = [
        p.relative_to(blind_root).as_posix()
        for p in files
        if p.suffix in DOC_SUFFIXES
    ]
    missing = sorted(set(docs) - set(key_by_path))
    phantom = sorted(set(key_by_path) - set(docs))
    if missing or phantom:
        raise CorruptError(
            "the answer key does not cover the blind tree "
            f"({len(missing)} unkeyed document(s), {len(phantom)} key line(s) "
            "with no document) — the corrupted key would inherit the gap; "
            "re-run python3 -m synthvdr answerkey first"
        )

    target = out_dir if out_dir is not None else room / CORRUPTED_DIR
    try:
        assert_safe_out_dir(target, room, conf, "the corrupted twin directory")
        assert_target_is_ours(target, CORRUPT_MARKER_NAME)
    except (UnsafeOutDirError, NotOwnedError) as exc:
        raise CorruptError(str(exc)) from exc
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    write_marker(target, CORRUPT_MARKER_NAME, CORRUPT_MARKER_TEXT)
    out_root = target / blind_root.name
    out_root.mkdir()

    section_dirs = sorted(
        {rel.split("/", 1)[0] for rel in docs if "/" in rel}
    )

    renamed = misfiled = noised = truncated = 0
    taken: set = set()
    log_rows = []
    new_key_rows = []

    for path in files:
        rel = path.relative_to(blind_root).as_posix()
        if path.suffix not in DOC_SUFFIXES:
            # Room artefacts and other non-documents ride along untouched.
            dest = out_root / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, dest)
            continue

        applied = []
        parent, name = (rel.rsplit("/", 1) + [""])[:2] if "/" in rel else ("", rel)
        if not name:
            parent, name = "", rel
        stem, suffix = Path(name).stem, Path(name).suffix

        if _hits(seed, rel, "rename", profile["rename_rate"]):
            stem = _rename(seed, rel, stem)
            applied.append("renamed")
        if len(section_dirs) > 1 and _hits(seed, rel, "misfile", profile["misfile_rate"]):
            others = [d for d in section_dirs if d != parent.split("/", 1)[0]]
            parent = others[_h(seed, rel, "misfile-dir") % len(others)]
            applied.append("misfiled")

        new_rel = f"{parent}/{stem}{suffix}" if parent else f"{stem}{suffix}"
        n = 2
        while new_rel in taken:
            new_rel = (
                f"{parent}/{stem} ({n}){suffix}" if parent else f"{stem} ({n}){suffix}"
            )
            n += 1
        taken.add(new_rel)

        text = path.read_text(encoding="utf-8")
        if suffix == ".md":
            if _hits(seed, rel, "noise", profile["noise_rate"]):
                text = _noise(seed, rel, text, profile["noise_char_rate"])
                applied.append("ocr-noise")
            if _hits(seed, rel, "truncate", profile["truncate_rate"]):
                text, did = _truncate(seed, rel, text)
                if did:
                    applied.append("truncated")

        dest = out_root / new_rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text, encoding="utf-8")

        renamed += "renamed" in applied
        misfiled += "misfiled" in applied
        noised += "ocr-noise" in applied
        truncated += "truncated" in applied
        log_rows.append({"original": rel, "corrupted": new_rel, "applied": applied})

        key_row = dict(key_by_path[rel])
        key_row["source_path"] = new_rel
        new_key_rows.append(key_row)

    new_key_rows.sort(key=lambda row: row["source_path"])
    (target / ANSWER_KEY_NAME).write_text(
        "".join(json.dumps(row) + "\n" for row in new_key_rows), encoding="utf-8"
    )
    log_rows.sort(key=lambda row: row["original"])
    (target / LOG_NAME).write_text(
        "".join(json.dumps(row) + "\n" for row in log_rows), encoding="utf-8"
    )

    return CorruptReport(
        documents=len(docs),
        renamed=renamed,
        misfiled=misfiled,
        noised=noised,
        truncated=truncated,
        out=target,
    )
