"""Generate index.md from _key/index-src/.

index.md is tool-facing and sits outside the blind tree. It is generated, never
hand-edited: gate 1 regenerates it and fails on any difference.

write_index_sources() clears and rewrites index_src on every call, and
index_src is a bare caller-supplied parameter with no room.conf path
validation behind it (see synthvdr.roomconf.PATH_KEYS: this path is not one
of them). Without a guard, pointing it at any existing directory would
silently delete every top-level .md file there. It reuses the shared
ownership guard in synthvdr.ownership rather than re-deriving one — see
that module's docstring for why a second, independently-written copy of
"prove ownership before deleting" is exactly what to avoid.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import List

from .domain import DomainPack
from .ownership import NotOwnedError
from .ownership import assert_target_is_ours as _assert_target_is_ours
from .ownership import write_marker
from .slots import Slot

INDEX_ENTRY = re.compile(r"^- (\d+\.\d+\.\d+) ", re.MULTILINE)

# Written at the root of index_src on every call, before any stale file is
# removed or new content written — see synthvdr.ownership for the algorithm
# and why it must be shared, not re-derived. Deliberately its own name and
# text, distinct from synthvdr.twin.MARKER_NAME and
# synthvdr.subset.SUBSET_MARKER_NAME: this directory is neither a flagged
# tree nor a subset, and a directory built by one writer must not be
# silently treated as "ours" by another just because they share a marker
# name. The name is a dotfile, so it is invisible to render_index(), which
# only reads "00_preamble.txt" by name and globs "*.md" — see
# test_marker_is_invisible_to_render_index for the check.
INDEX_SRC_MARKER_NAME = ".synthvdr-index-src"

INDEX_SRC_MARKER_TEXT = (
    "Generated by synthvdr (synthvdr/index_build.py). This directory's "
    ".md files are deleted and rewritten on every index build, so nothing "
    "here is safe to hand-edit or store. Removing this marker file makes "
    "the directory un-rebuildable in place: synthvdr refuses to delete "
    "stale files from a non-empty directory it cannot prove it created, "
    "and will stop rather than destroy your data.\n"
)


class IndexBuildError(Exception):
    """index_src cannot be safely (re)written."""


PREAMBLE = (
    "This is the contents list for the documents made available in connection with "
    "the proposed transaction. Documents are numbered by section, sub-section and "
    "item. Numbering is stable: an item keeps its number for the life of the "
    "process.\n"
)

# Acronyms that should be uppercased in presentation (singular forms only)
ACRONYMS = {
    "vat", "nda", "cpse", "hse", "qms", "ncr", "capa", "dc", "ropa", "dpia",
    "jv", "esg", "it", "spa", "epc", "qa",
}

# Minimum length of the singular form before a trailing 's' is treated as a
# pluralised acronym. Without this floor, 'it' (an acronym) makes ordinary
# words like 'its' render as 'ITs'.
_MIN_ACRONYM_LEN_FOR_PLURAL = 3

# The word run that collapses to 'W&I'. Titles are compound strings — a
# section heading gets the bare words, but every document title in that
# subsection gets the words plus a trailing ordinal ('w and i 01'). A
# whole-string equality check only ever matches the heading; matching the
# run wherever it occurs handles both.
_W_AND_I_RUN = ("w", "and", "i")


def _titleise(text: str) -> str:
    """Render text in sentence case with acronyms uppercased.

    - Capitalises the first letter only (sentence case, not title case)
    - Acronyms are uppercased in place: 'vat' -> 'VAT', 'nda' -> 'NDA'
    - Plural acronyms keep the acronym uppercased and add lowercase 's':
      'ndas' -> 'NDAs'. Only fires when the singular form is at least
      `_MIN_ACRONYM_LEN_FOR_PLURAL` characters, so short acronyms don't
      swallow ordinary words ('its' stays 'Its', not 'ITs').
    - The token run 'w', 'and', 'i' collapses to 'W&I' wherever it appears
      in the word list, including inside a longer, ordinal-suffixed title.

    Examples:
        'statutory accounts' -> 'Statutory accounts'
        'cpse replies' -> 'CPSE replies'
        'nda' -> 'NDA'
        'ndas' -> 'NDAs'
        'w and i' -> 'W&I'
        'w and i 01' -> 'W&I 01'
        'its' -> 'Its'
    """
    words = text.split()

    # Collapse every occurrence of the 'w and i' run into a single 'W&I'
    # token before the per-word pass, so it works whether it's the whole
    # string or has a trailing ordinal (or, in principle, a leading one).
    collapsed: List[str] = []
    run_len = len(_W_AND_I_RUN)
    idx = 0
    while idx < len(words):
        window = tuple(w.lower() for w in words[idx : idx + run_len])
        if window == _W_AND_I_RUN:
            collapsed.append("W&I")
            idx += run_len
        else:
            collapsed.append(words[idx])
            idx += 1
    words = collapsed

    result = []
    for i, word in enumerate(words):
        if word == "W&I":
            result.append(word)
            continue

        word_lower = word.lower()

        if word_lower in ACRONYMS:
            result.append(word_lower.upper())
        elif (
            word_lower.endswith("s")
            and len(word_lower) - 1 >= _MIN_ACRONYM_LEN_FOR_PLURAL
            and word_lower[:-1] in ACRONYMS
        ):
            # 'ndas' -> 'NDAs', not 'NDAS': the plural 's' is not part of
            # the acronym, so it is appended in lowercase after the uppercasing
            # rather than swept up by it. The length floor above is what stops
            # this branch swallowing an ordinary word whose stem happens to be
            # a short acronym — see the docstring's 'its' example.
            result.append(word_lower[:-1].upper() + "s")
        elif i == 0:
            # Sentence case, not title case, and the whole reason this
            # function is not `str.title()`: index.md titles are prose
            # headings, and title-casing them would also destroy the acronym
            # handling above ('VAT' -> 'Vat').
            result.append(word_lower.capitalize())
        else:
            # Lowercased rather than passed through: the input is a slug, so
            # incidental capitals in it are noise, not intent.
            result.append(word_lower)

    return " ".join(result)


def write_index_sources(slots: List[Slot], pack: DomainPack, index_src: Path) -> None:
    # index_src is a bare parameter with no room.conf validation behind it.
    # Prove this tool created it (or that it's empty/nonexistent) BEFORE
    # deleting anything under it. See synthvdr.ownership for the algorithm.
    try:
        _assert_target_is_ours(index_src, INDEX_SRC_MARKER_NAME)
    except NotOwnedError as exc:
        raise IndexBuildError(str(exc)) from exc

    index_src.mkdir(parents=True, exist_ok=True)
    # Marker down before any stale file is removed or new content is
    # written, so a run that dies part-way still leaves a directory the
    # next run may still clear, never a permanent lockout.
    write_marker(index_src, INDEX_SRC_MARKER_NAME, INDEX_SRC_MARKER_TEXT)

    # Clean up stale section files to ensure exact regeneration
    for stale in index_src.glob("*.md"):
        stale.unlink()
    (index_src / "00_preamble.txt").write_text(PREAMBLE, encoding="utf-8")
    for section in pack.sections:
        rows = [s for s in slots if s.section_dir == section.dir_name]
        lines = [f"## {section.number}. {section.title}", ""]
        current_sub = None
        for slot in rows:
            if slot.subsection != current_sub:
                current_sub = slot.subsection
                pretty = current_sub.split("_", 1)[1].replace("-", " ")
                pretty = _titleise(pretty)
                lines.append(f"### {current_sub.split('_')[0]} {pretty}")
                lines.append("")
            title = slot.slug.split("_", 1)[1].replace("-", " ")
            title = _titleise(title)
            lines.append(f"- {slot.slot_id} {title}")
        lines.append("")
        (index_src / f"{section.dir_name}.md").write_text("\n".join(lines), encoding="utf-8")


def render_index(index_src: Path) -> str:
    preamble = (index_src / "00_preamble.txt").read_text(encoding="utf-8").rstrip("\n")
    parts = [preamble, ""]
    for path in sorted(p for p in index_src.glob("*.md")):
        parts.append(path.read_text(encoding="utf-8").rstrip("\n"))
        parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


def count_slots(index_text: str) -> int:
    return len(INDEX_ENTRY.findall(index_text))
