"""Deterministic subset builder.

Every planted finding survives into the subset with its full evidence chain;
filler is chosen by hash so repeat runs are byte-identical. check_subset()
reconciles an existing subset and writes nothing — it is gate 11.
"""

from __future__ import annotations

import csv
import hashlib
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

import yaml

from .ownership import NotOwnedError, UnsafeOutDirError, assert_safe_out_dir
from .ownership import assert_target_is_ours as _assert_target_is_ours
from .ownership import write_marker
from .roomconf import RoomConf
from .schema import FindingSet


class SubsetError(Exception):
    """The requested subset output directory cannot be used safely."""


# Written at the root of the subset directory on every build, before any
# document — see synthvdr.ownership for the algorithm and why it must be
# shared, not re-derived. Deliberately its own name and text, distinct
# from synthvdr.twin.MARKER_NAME: this directory is a subset, not a
# flagged tree, and a directory built by one writer must not be silently
# treated as "ours" by the other just because they share a marker name.
SUBSET_MARKER_NAME = ".synthvdr-subset"

SUBSET_MARKER_TEXT = (
    "Generated by synthvdr (synthvdr/subset.py). This whole directory is "
    "deleted and rebuilt on every subset build, so nothing here is safe to "
    "edit or store. Removing this marker file makes the directory "
    "un-rebuildable in place: synthvdr refuses to delete a non-empty "
    "directory it cannot prove it created, and will stop rather than "
    "destroy your data.\n"
)


@dataclass
class SubsetReport:
    total: int = 0
    evidence: int = 0
    filler: int = 0
    findings_covered: int = 0
    findings_total: int = 0
    errors: List[str] = field(default_factory=list)

    @property
    def complete(self) -> bool:
        return not self.errors and self.findings_covered == self.findings_total


def _hash_key(rel: str) -> str:
    return hashlib.sha256(rel.encode("utf-8")).hexdigest()


def select_subset(room: Path, conf: RoomConf, findings: FindingSet, total: int) -> List[str]:
    blind_root = room / conf.get("BLIND_TREE")
    everything = sorted(
        p.relative_to(blind_root).as_posix() for p in blind_root.rglob("*") if p.is_file()
    )
    evidence = sorted(findings.all_evidence_paths() & set(everything))
    filler_pool = [rel for rel in everything if rel not in set(evidence)]
    filler_pool.sort(key=_hash_key)
    shortfall = max(0, total - len(evidence))
    return evidence + filler_pool[:shortfall]


def _assert_safe_out_dir(out_dir: Path, room: Path, conf: RoomConf) -> None:
    """The shared out_dir safety rule (synthvdr.ownership.assert_safe_out_dir),
    re-raised as SubsetError so a caller of this module sees one exception
    type. The rule itself lived here first; it moved to ownership.py when
    the corruption stage grew an --out of its own, for the same reason the
    marker guard is shared: two copies of a safety rule diverge, and the
    divergence is where the bypass lives.
    """
    try:
        assert_safe_out_dir(out_dir, room, conf, "the subset output directory")
    except UnsafeOutDirError as exc:
        raise SubsetError(str(exc)) from exc


def build_subset(
    room: Path, conf: RoomConf, findings: FindingSet, total: int, out_dir: Path
) -> SubsetReport:
    _assert_safe_out_dir(out_dir, room, conf)
    # out_dir may legitimately live OUTSIDE the room entirely (a caller
    # writing an eval subset to /tmp, say) — _assert_safe_out_dir does not
    # and cannot cover that case, since it only knows about paths inside
    # the room. This is the Task-7 ownership guard: out_dir is about to be
    # shutil.rmtree'd, so prove it was built by THIS function before an
    # existing, unrelated, non-empty directory anywhere is destroyed.
    try:
        _assert_target_is_ours(out_dir, SUBSET_MARKER_NAME)
    except NotOwnedError as exc:
        raise SubsetError(str(exc)) from exc

    blind_root = room / conf.get("BLIND_TREE")
    key_root = room / conf.get("KEY_ROOT")
    selected = select_subset(room, conf, findings, total)
    evidence = findings.all_evidence_paths()

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    # Marker before any document: a build that dies part-way still leaves
    # a directory the next build is allowed to clear, never a lockout.
    write_marker(out_dir, SUBSET_MARKER_NAME, SUBSET_MARKER_TEXT)
    for rel in selected:
        target = out_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(blind_root / rel, target)

    key_root.mkdir(parents=True, exist_ok=True)
    with (key_root / "subset-manifest.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["rel_path", "role"])
        for rel in selected:
            writer.writerow([rel, "evidence" if rel in evidence else "filler"])

    covered = [f for f in findings.findings if set(f.evidence_paths()) <= set(selected)]
    (key_root / "subset-key.yaml").write_text(
        yaml.safe_dump(
            {
                "schema_version": 1,
                "room": findings.room,
                "subset_documents": len(selected),
                "findings": [
                    {"id": f.id, "severity": f.severity, "evidence": f.evidence_paths()}
                    for f in covered
                ],
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    return check_subset(room, conf, findings, out_dir=out_dir)


def check_subset(
    room: Path, conf: RoomConf, findings: FindingSet, out_dir: Optional[Path] = None
) -> SubsetReport:
    out_dir = out_dir or (room / "subset")
    report = SubsetReport(findings_total=len(findings.findings))
    if not out_dir.is_dir():
        report.errors.append(f"{out_dir} does not exist")
        return report

    # The marker is infrastructure the subset itself writes, not a
    # document — it must never inflate .total/.evidence/.filler, exactly as
    # synthvdr.twin.MARKER_NAME must never inflate a TwinReport (see that
    # module's gate coverage). Excluded by exact relative path, not by
    # suffix: subset documents are not guaranteed to be markdown (evidence
    # may be a CSV register, say), so a suffix filter would risk excluding
    # a real document instead.
    present = {
        p.relative_to(out_dir).as_posix()
        for p in out_dir.rglob("*")
        if p.is_file() and p.relative_to(out_dir).as_posix() != SUBSET_MARKER_NAME
    }
    report.total = len(present)
    evidence_paths = findings.all_evidence_paths()
    report.evidence = len(evidence_paths & present)
    report.filler = report.total - report.evidence

    if not findings.findings:
        report.errors.append(
            "no findings parsed from the answer key — refusing to report a reconciled subset"
        )
        return report

    for finding in findings.findings:
        missing = [p for p in finding.evidence_paths() if p not in present]
        if missing:
            report.errors.append(f"{finding.id}: evidence missing from subset: {', '.join(missing)}")
        else:
            report.findings_covered += 1
    return report
