#!/usr/bin/env python3
"""Build the Legora pack: synth-vdr's skills for Legora's skill builder.

Legora cannot install a Claude Code plugin. It takes skills in the open
SKILL.md format — an instruction and reference documents, as Markdown or
Word, as a folder or a zip — so this writes that pack to dist/legora from the
sources in legora/: each skill's SKILL.md and hand-written references, the
README, and a sections page generated from domain/ma/sections.yaml so the
folders it names cannot drift from the ones rooms are built with. The probe
under legora/probe/ is a separate skill with its own zip and is not built
here.

Each SKILL.md goes out with one line under its heading naming the build,
`Built from synth-vdr <version> · domain pack ma`, the version read from the
package. An uploaded skill otherwise says nothing about where it came from:
gb-docclass found a Drive folder labelled 1.2.4 holding a 1.2.3 run. The
review skill asks the agent to copy that line into its report, so the report
names its build too.

Two builds of one commit are the same bytes: zip entries and the Word copies'
core properties are pinned to 1980-01-01, the earliest a zip entry can
record. Without that, "this pack changed" cannot be told from "this pack was
built again".

The output folder is deleted and rebuilt, so the builder writes a marker at
its root and refuses to delete a non-empty folder without one
(synthvdr.ownership), the rule every other delete-and-rebuild writer here
follows.

--check renders the Markdown afresh and fails if --out is missing or any
Markdown file in it differs from its source, naming each one.

Usage:
    tools/build_legora_pack.py [--out DIR] [--no-docx]
    tools/build_legora_pack.py --check [--out DIR]
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from typing import Dict, List

import synthvdr
from synthvdr.domain import DEFAULT_DOMAIN_ROOT, load_domain
from synthvdr.ownership import NotOwnedError, assert_target_is_ours, write_marker

# The one owner of subfolder naming, so the page cannot spell a folder
# differently from the rooms. Private by name, shared by design: the plugin
# surface tests import it for the same reason.
from synthvdr.slots import _subsection_name

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCES = ROOT / "legora"
DEFAULT_OUT = ROOT / "dist" / "legora"

# The one generated reference, and the skill that carries it.
SECTIONS_SKILL = "review-a-test-data-room"
SECTIONS_PAGE = "1-the-twenty-sections.md"
DOMAIN_PACK = "ma"

PACK_MARKER = ".synthvdr-legora-pack"
PACK_MARKER_TEXT = (
    "Generated by tools/build_legora_pack.py. This whole folder is deleted and "
    "rebuilt on every build; edit the sources under legora/ instead.\n"
)

FIXED_TIME = (1980, 1, 1, 0, 0, 0)
FIXED_STAMP = "1980-01-01T00:00:00Z"
_DCTERM = re.compile(r"(<dcterms:(created|modified)[^>]*>)[^<]*(</dcterms:\2>)")


class BuildError(Exception):
    """The pack cannot be built from these sources."""


def skills(sources: Path) -> List[str]:
    return sorted(p.name for p in (sources / "skills").iterdir() if (p / "SKILL.md").is_file())


def version_line() -> str:
    return f"Built from synth-vdr {synthvdr.__version__} · domain pack {DOMAIN_PACK}"


def stamped(skill_md: Path) -> str:
    """The SKILL.md with its version line under the heading, where a reader
    looking for it finds it first and a model reading the instructions passes
    straight over it."""
    lines = skill_md.read_text(encoding="utf-8").split("\n")
    for index, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[: index + 1] + ["", version_line()] + lines[index + 1 :])
    raise BuildError(f"{skill_md} has no '# ' heading to put the version line under")


def sections_page() -> str:
    domain = load_domain(DEFAULT_DOMAIN_ROOT)
    lines = [
        "# The twenty sections",
        "",
        "Every document in the room sits in one of these numbered folders, inside one "
        "of its subfolders, and every path you cite starts at the numbered folder. A "
        "room may leave some sections or subfolders out.",
        "",
    ]
    for section in domain.sections:
        subfolders = ", ".join(
            f"`{_subsection_name(section, index)}`" for index in range(len(section.subsections))
        )
        lines.append(f"- `{section.dir_name}`, {section.title}: {subfolders}")
    return "\n".join(lines) + "\n"


def markdown_files(sources: Path) -> Dict[str, str]:
    """Every Markdown file the pack holds, by its path in the pack."""
    files = {"README.md": (sources / "README.md").read_text(encoding="utf-8")}
    for skill in skills(sources):
        folder = sources / "skills" / skill
        files[f"skills/{skill}/SKILL.md"] = stamped(folder / "SKILL.md")
        if skill == SECTIONS_SKILL:
            files[f"skills/{skill}/references/{SECTIONS_PAGE}"] = sections_page()
        references = folder / "references"
        if references.is_dir():
            for reference in sorted(references.glob("*.md")):
                files[f"skills/{skill}/references/{reference.name}"] = reference.read_text(encoding="utf-8")
    return dict(sorted(files.items()))


def _write_fixed(archive: zipfile.ZipFile, name: str, data: bytes) -> None:
    info = zipfile.ZipInfo(name, date_time=FIXED_TIME)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    archive.writestr(info, data)


def repack_without_the_clock(path: Path) -> None:
    """Rewrite a .docx so the same Markdown always gives the same bytes: pandoc
    dates the core properties and every entry it writes."""
    with zipfile.ZipFile(path) as archive:
        entries = [(info.filename, archive.read(info.filename)) for info in archive.infolist()]
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, data in entries:
            if name == "docProps/core.xml":
                data = _DCTERM.sub(rf"\g<1>{FIXED_STAMP}\g<3>", data.decode("utf-8")).encode("utf-8")
            _write_fixed(archive, name, data)


def build(sources: Path, out: Path, docx: bool) -> List[str]:
    """Build the pack; return one summary line per skill."""
    if docx and not shutil.which("pandoc"):
        raise BuildError(
            "pandoc is not installed, and the Word copies of the references need it. "
            "Install it (brew install pandoc) or pass --no-docx."
        )
    files = markdown_files(sources)
    assert_target_is_ours(out, PACK_MARKER)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    write_marker(out, PACK_MARKER, PACK_MARKER_TEXT)
    for rel, text in files.items():
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        if docx and "/references/" in rel:
            word = target.with_suffix(".docx")
            result = subprocess.run(
                ["pandoc", str(target), "-o", str(word)], capture_output=True, text=True
            )
            if result.returncode != 0:
                raise BuildError(f"pandoc could not convert {rel}: {result.stderr.strip()}")
            repack_without_the_clock(word)
    summary = []
    for skill in skills(sources):
        folder = out / "skills" / skill
        with zipfile.ZipFile(out / "skills" / f"{skill}.zip", "w", zipfile.ZIP_DEFLATED) as archive:
            for path in sorted(folder.rglob("*")):
                if path.is_file():
                    _write_fixed(archive, f"{skill}/{path.relative_to(folder).as_posix()}", path.read_bytes())
        references = len([rel for rel in files if rel.startswith(f"skills/{skill}/references/")])
        word = " (Markdown and Word)" if docx and references else ""
        summary.append(f"  {skill}: SKILL.md, {references} reference(s){word}, zipped")
    return summary


def check(sources: Path, out: Path) -> List[str]:
    """Every way the pack at `out` differs from a fresh render of `sources`."""
    if not out.is_dir():
        return [f"{out} does not exist; build the pack first (make legora)"]
    expected = markdown_files(sources)
    stale = []
    for rel, text in expected.items():
        built = out / rel
        if not built.is_file():
            stale.append(f"{rel} is missing from the built pack")
        elif built.read_text(encoding="utf-8") != text:
            stale.append(f"{rel} in the built pack differs from its source")
    for path in sorted(out.rglob("*.md")):
        rel = path.relative_to(out).as_posix()
        if rel not in expected:
            stale.append(f"{rel} is in the built pack but has no source")
    return stale


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="default: dist/legora")
    parser.add_argument("--sources", type=Path, default=DEFAULT_SOURCES, help="default: legora/")
    parser.add_argument("--no-docx", action="store_true", help="skip the Word copies of the references")
    parser.add_argument(
        "--check", action="store_true", help="build nothing; fail if the pack at --out lags its sources"
    )
    args = parser.parse_args(argv)
    try:
        if args.check:
            stale = check(args.sources, args.out)
            if stale:
                print("The Legora pack is stale:")
                for line in stale:
                    print(f"  {line}")
                print("Rebuild it: make legora")
                return 1
            print("The Legora pack matches its sources.")
            return 0
        summary = build(args.sources, args.out, docx=not args.no_docx)
    except (BuildError, NotOwnedError) as exc:
        print(f"build_legora_pack: {exc}", file=sys.stderr)
        return 2
    print("\n".join(summary))
    print(f"Legora pack built in {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
